// Classificacao compartilhada pelo upload. Novos cargos aprovados em 04/10/2026.
function chaveCargo(cargo) {
    return String(cargo || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '')
        .toUpperCase().trim().replace(/\s+/g, ' ');
}
const CARGO_CLASSE = {
    'OP. MAQ. FLORESTAIS I': 'OPF',
    'OPERADOR DE CAMINHAO MUNCK': 'OPF',
    'OP DE PÁ CARREGADEIRA': 'OPF',
    'OPERADOR DE PA CARREGADEIRA': 'OPF',
    'OPERADOR DE MUNCK': 'OPF',
    'COORDENADOR': 'COF',
    'COORDENADOR DE SIVILCUTURA': 'COF',
    'COORDENADOR SILVICULTURA': 'COF',
    'AUXILIAR DE LIDER': 'LDF',
    'LIDER DE EQUIPE': 'LDF',
    'LIDER DE MANUTENCAO': 'LDF',
    'LIDER DE MAQUINAS PESADAS': 'LDF',
    'LIDER FLORESTAL': 'LDF',
    'BORRACHEIRO DE CAMPO': 'MEC',
    'MECANICO': 'MEC',
    'MECANICO I': 'MEC',
    'AUX. MECANICO': 'MEC',
    'MOTORISTA': 'MCM',
    'MOTORISTA CAMINHAO': 'MCM',
    'MOTORISTA CAMINHAO PIPA': 'MCM',
    'MOTORISTA COMBOIO': 'MCM',
    'MOTORISTA CARRETA CACAMBA': 'MCR',
    'MOTORISTA CAMINHAO PRANCHA': 'MCM',
    'SUPERVISOR SILVICULTURA': 'SPF',
    'SUPERVISOR SILVICULTURA E FROTA': 'SPF',
    'TRABALHADOR FLORESTAL': 'TRF',
    'ANALISTA ADMINISTRATIVO': 'ADM',
    'ANALISTA ADMINISTRATIVO I': 'ADM',
    'ANALISTA DE PLANEJAMENTO': 'ADM',
    'ANALISTA DE PLANEJAMENTO JR': 'ADM',
    'ANALISTA SEGURANÇA DO TRABALHO': 'ADM',
    'ANALISTA DE SAUDE OCUPACIONAL': 'ADM',
    'APRENDIZ ADMINISTRATIVO': 'ADM',
    'ASSISTENTE ADMINISTRATIVO': 'ADM',
    'ASSISTENTE DE PCP': 'ADM',
    'ASSISTENTE DE PCP I': 'ADM',
    'ASSISTENTE DE TECNOLOGIA DA INFORMACAO': 'ADM',
    'AUXILIAR ADMINISTRATIVO': 'ADM',
    'AUXILIAR ADMINISTRATIVO I': 'ADM',
    'AUXILIAR DE CONTROLE': 'ADM',
    'AUXILIAR DE QUALIDADE': 'ADM',
    'AUXILIAR FINANCEIRO': 'ADM',
    'AUXILIAR TECNICO DE QUALIDADE': 'ADM',
    'COMPRADOR': 'ADM',
    'COMPRADOR JUNIOR': 'ADM',
    'ESTAGIÁRIO ADMINISTRATIVO': 'ADM',
    'GERENTE ADMINISTRATIVO': 'ADM',
    'GERENTE FINANCEIRO': 'ADM',
    'GERENTE OPERACIONAL': 'ADM',
    'MONITOR DE ALOJAMENTO': 'ADM',
    'MONITOR FLORESTAL': 'ADM',
    'SERVICOS GERAIS': 'ADM',
    'SUPERVISOR ADMINISTRATIVO': 'ADM',
    'SUPERVISOR DE SUPRIMENTOS': 'ADM',
    'SUPERVISOR(A) ADMINISTRATIVO': 'ADM',
    'SUPERVISOR(A) FINANCEIRO': 'ADM',
    'SUPERVISOR DE PCP': 'ADM',
    'TECNICO DE QUALIDADE': 'ADM',
    'TECNICO SEGURANCA DO TRABALHO': 'ADM',
    'TECNICO SEGURANCA DO TRABALHO PLENO': 'ADM',
    'TECNICO EM SEGURANCA DO TRABALHO': 'ADM',
    'ANALISTA DE PCP JUNIOR': 'ADM'
};
const CARGO_FUNCAO_EXECUTANTE = {
    'OP. MAQ. FLORESTAIS I': 'OPERADOR',
    'OPERADOR DE CAMINHAO MUNCK': 'OPERADOR',
    'OP DE PÁ CARREGADEIRA': 'OPERADOR',
    'OPERADOR DE PA CARREGADEIRA': 'OPERADOR',
    'OPERADOR DE MUNCK': 'OPERADOR',
    'COORDENADOR': 'COORDENADOR',
    'COORDENADOR DE SIVILCUTURA': 'COORDENADOR',
    'COORDENADOR SILVICULTURA': 'COORDENADOR',
    'AUXILIAR DE LIDER': 'LIDER',
    'LIDER DE EQUIPE': 'LIDER',
    'LIDER DE MANUTENCAO': 'LIDER',
    'LIDER DE MAQUINAS PESADAS': 'LIDER',
    'LIDER FLORESTAL': 'LIDER',
    'BORRACHEIRO DE CAMPO': 'MECANICO',
    'MECANICO': 'MECANICO',
    'MECANICO I': 'MECANICO',
    'AUX. MECANICO': 'MECANICO',
    'MOTORISTA': 'MOTORISTA',
    'MOTORISTA CAMINHAO': 'MOTORISTA',
    'MOTORISTA CAMINHAO PIPA': 'MOTORISTA',
    'MOTORISTA COMBOIO': 'MOTORISTA',
    'MOTORISTA CARRETA CACAMBA': 'MOTORISTA',
    'MOTORISTA CAMINHAO PRANCHA': 'MOTORISTA',
    'SUPERVISOR SILVICULTURA': 'SUPERVISOR',
    'SUPERVISOR SILVICULTURA E FROTA': 'SUPERVISOR',
    'TRABALHADOR FLORESTAL': 'TRABALHADOR',
    'ANALISTA ADMINISTRATIVO': 'ADMINISTRATIVO',
    'ANALISTA ADMINISTRATIVO I': 'ADMINISTRATIVO',
    'ANALISTA DE PLANEJAMENTO': 'ADMINISTRATIVO',
    'ANALISTA DE PLANEJAMENTO JR': 'ADMINISTRATIVO',
    'ANALISTA SEGURANÇA DO TRABALHO': 'ADMINISTRATIVO',
    'ANALISTA DE SAUDE OCUPACIONAL': 'ADMINISTRATIVO',
    'APRENDIZ ADMINISTRATIVO': 'ADMINISTRATIVO',
    'ASSISTENTE ADMINISTRATIVO': 'ADMINISTRATIVO',
    'ASSISTENTE DE PCP': 'ADMINISTRATIVO',
    'ASSISTENTE DE PCP I': 'ADMINISTRATIVO',
    'ASSISTENTE DE TECNOLOGIA DA INFORMACAO': 'ADMINISTRATIVO',
    'AUXILIAR ADMINISTRATIVO': 'ADMINISTRATIVO',
    'AUXILIAR ADMINISTRATIVO I': 'ADMINISTRATIVO',
    'AUXILIAR DE CONTROLE': 'ADMINISTRATIVO',
    'AUXILIAR DE QUALIDADE': 'ADMINISTRATIVO',
    'AUXILIAR FINANCEIRO': 'ADMINISTRATIVO',
    'AUXILIAR TECNICO DE QUALIDADE': 'ADMINISTRATIVO',
    'COMPRADOR': 'ADMINISTRATIVO',
    'COMPRADOR JUNIOR': 'ADMINISTRATIVO',
    'ESTAGIÁRIO ADMINISTRATIVO': 'ADMINISTRATIVO',
    'GERENTE ADMINISTRATIVO': 'ADMINISTRATIVO',
    'GERENTE FINANCEIRO': 'ADMINISTRATIVO',
    'GERENTE OPERACIONAL': 'ADMINISTRATIVO',
    'MONITOR DE ALOJAMENTO': 'ADMINISTRATIVO',
    'MONITOR FLORESTAL': 'ADMINISTRATIVO',
    'SERVICOS GERAIS': 'ADMINISTRATIVO',
    'SUPERVISOR ADMINISTRATIVO': 'ADMINISTRATIVO',
    'SUPERVISOR DE SUPRIMENTOS': 'ADMINISTRATIVO',
    'SUPERVISOR(A) ADMINISTRATIVO': 'ADMINISTRATIVO',
    'SUPERVISOR(A) FINANCEIRO': 'ADMINISTRATIVO',
    'SUPERVISOR DE PCP': 'ADMINISTRATIVO',
    'TECNICO DE QUALIDADE': 'ADMINISTRATIVO',
    'TECNICO SEGURANCA DO TRABALHO': 'ADMINISTRATIVO',
    'TECNICO SEGURANCA DO TRABALHO PLENO': 'ADMINISTRATIVO',
    'TECNICO EM SEGURANCA DO TRABALHO': 'ADMINISTRATIVO',
    'ANALISTA DE PCP JUNIOR': 'ADMINISTRATIVO'
};
const CARGOS_APROVADOS = [
    [
        "OPERADOR DE MAQUINA FLORESTAL I",
        "OPF",
        "OPERADOR"
    ],
    [
        "TRABALHADOR FLORESTAL BRIGADISTA",
        "TRF",
        "TRABALHADOR"
    ],
    [
        "MOTORISTA BRIGADISTA",
        "MCM",
        "MOTORISTA"
    ],
    [
        "ANALISTA FINANCEIRO",
        "ADM",
        "ADMINISTRATIVO"
    ],
    [
        "ASSISTENTE DE FACILITIES",
        "ADM",
        "ADMINISTRATIVO"
    ],
    [
        "AUXILIAR DE SEGURANCA",
        "ADM",
        "ADMINISTRATIVO"
    ],
    [
        "ENFERMEIRO (A) DO TRABALHO",
        "ADM",
        "ADMINISTRATIVO"
    ],
    [
        "MOTORISTA DE CARRO LEVE",
        "MCM",
        "MOTORISTA"
    ],
    [
        "ANALISTA CONTABIL",
        "ADM",
        "ADMINISTRATIVO"
    ],
    [
        "ANALISTA DE PROCESSOS E DESENVOLVIMENTO ORGANIZACIONAL",
        "ADM",
        "ADMINISTRATIVO"
    ],
    [
        "ANALISTA DE QUALIDADE DE SILVICULTURA JR",
        "ADM",
        "ADMINISTRATIVO"
    ],
    [
        "OPERADOR DE RETROESCAVADEIRA",
        "OPF",
        "OPERADOR"
    ],
    [
        "SUPERVISOR DE MANUTENCAO",
        "ADM",
        "ADMINISTRATIVO"
    ],
    [
        "SUPERVISOR DE QUALIDADE",
        "ADM",
        "ADMINISTRATIVO"
    ],
    [
        "SUPERVISOR DE TECNOLOGIA E DESENVOLVIMENTO DE SISTEMAS",
        "ADM",
        "ADMINISTRATIVO"
    ]
];
const classes = new Map(Object.entries(CARGO_CLASSE).map(([cargo, classe]) => [chaveCargo(cargo), classe]));
const funcoes = new Map(Object.entries(CARGO_FUNCAO_EXECUTANTE).map(([cargo, funcao]) => [chaveCargo(cargo), funcao]));
for (const [cargo, classe, funcao] of CARGOS_APROVADOS) {
    classes.set(chaveCargo(cargo), classe);
    funcoes.set(chaveCargo(cargo), funcao);
}
function obterClasse(cargo) {
    return classes.get(chaveCargo(cargo)) || 'OUT';
}
function obterFuncaoExecutante(cargo) {
    return funcoes.get(chaveCargo(cargo)) || (cargo ? String(cargo).trim().split(/\s+/)[0].toUpperCase() : null);
}
module.exports = { obterClasse, obterFuncaoExecutante, chaveCargo, CARGOS_APROVADOS };
